import { Perfil } from "./store/useAppStore";

export const PERFIL_INICIAL: Omit<Perfil, 'ID_PERFIL'> = {
  NOMBRE_PERFIL: '',
  CLIENTE: 'SMURFIT WESTROCK',
  PROYECTO: 'CALDERA BIOMASA',
  CONTRATO: 'C.O.654',
  REVISION: '0',
  FECHA_REVISION: '26-09-2026',
  FECHA: new Date().toISOString().split('T')[0],
  TAG_CABLE_SWC: '',
  TAGNAME: '',
  DESCRIPCION: '',
  TIPO_CABLE: '',
  UBICACION: '',
  OBSERVACION: '',
  NORMA_PROCEDIMIENTO: '121.18-PEVS-GEN-IEC-DRA',
  TIPO_PRUEBA_PLANO: false,
  TIPO_PRUEBA_LOOP: true,
  TIPO_PRUEBA_FUNC_SIM: false,
  TIPO_PRUEBA_FUNC_LINEA: false,
  EQUIPO_PRUEBA_1: 'MEGGER TIERRA / AISLAMIENTO',
  CERT_FECHA_1: '',
  EQUIPO_PRUEBA_2: 'PINZA VOLTIAMPERIMETRICA',
  CERT_FECHA_2: '',
  LOOP_C1: 'EQUIPO',
  LOOP_C2: 'CORRIENTE / TENSIÓN',
  LOOP_C3: 'TEMPERATURA / PRESIÓN',
  L1_C1: 'DCS / PLC',
  L1_C2: '',
  L1_C3: '',
  L2_C1: 'MULTÍMETRO / PATRÓN',
  L2_C2: '',
  L2_C3: '',
  L3_C1: 'INSTRUMENTO',
  L3_C2: '',
  L3_C3: '',
  INSP_4_1: 'SI',
  OBS_4_1: '',
  LABEL_4_1: 'Condiciones físicas (evidencias de golpes, rayones, pantalla)',
  INSP_4_2: 'SI',
  OBS_4_2: '',
  LABEL_4_2: 'Conductor e hilo (aislamiento/continuidad)',
  INSP_4_3: 'SI',
  OBS_4_3: '',
  LABEL_4_3: 'Identificación y marquillado',
  INSP_4_4: 'SI',
  OBS_4_4: '',
  LABEL_4_4: 'Instalación y soportaje seguro',
  COMENTARIOS: 'SE REALIZA PRUEBA DE LAZO SATISFACTORIA. EQUIPO EN LINEA.',
  ELABORO_NOMBRE: '',
  ELABORO_CARGO: '',
  ELABORO_FIRMA: '',
  REVISO_NOMBRE: '',
  REVISO_CARGO: '',
  REVISO_FIRMA: '',
  APROBO_NOMBRE: '',
  APROBO_CARGO: '',
  APROBO_FIRMA: '',
};
